version: '3'
services:
  app:
    image: <YOUR REPOSITORY IMAGE URL e.g. username/image_name:latest>
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      resources:
        limits:
          memory: 128M
      replicas: 3 # Number of replicas you want
    depends_on:
      - db
    environment:
      - APP_KEY=<YOUR APP KEY> # TODO: prefer secrets for this
      - APP_DEBUG=false
      - APP_URL=<YOUR DOMAIN>
      - APP_ENV=production
      - LOG_CHANNEL=errorlog
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=supersecretpasswordyoureallyshouldchange
  db:
    image: postgres:10.6-alpine
    volumes:
      - laravel_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersecretpasswordyoureallyshouldchange
    deploy:
      mode: replicated
      replicas: 1
volumes:
  # TODO: improve database volume
  laravel_postgres:
